/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciotarjetabip2;

/**
 *
 * @author Matio_000
 */

import javax.swing.JOptionPane;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private Manejadora man=new Manejadora();
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnqTarjeta = new javax.swing.JMenu();
        mnuIngresar = new javax.swing.JMenuItem();
        mnuCargar = new javax.swing.JMenuItem();
        mnuModificar = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();
        mnqVer = new javax.swing.JMenu();
        mnqMostrarTodo = new javax.swing.JMenuItem();
        mnqViajar = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciotarjetabip2/Dibujo_Tarjeta_Bip!.png"))); // NOI18N

        mnqTarjeta.setText("TarjetaBip");

        mnuIngresar.setText("Ingresar Tarjeta");
        mnuIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngresarActionPerformed(evt);
            }
        });
        mnqTarjeta.add(mnuIngresar);

        mnuCargar.setText("Cargar Tarjeta");
        mnuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargarActionPerformed(evt);
            }
        });
        mnqTarjeta.add(mnuCargar);

        mnuModificar.setText("Modificar Tarjeta");
        mnuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarActionPerformed(evt);
            }
        });
        mnqTarjeta.add(mnuModificar);

        mnuEliminar.setText("Eliminar Tarjeta");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        mnqTarjeta.add(mnuEliminar);

        jMenuBar1.add(mnqTarjeta);

        mnqVer.setText("Ver");

        mnqMostrarTodo.setText("Buscar Una Tarjeta o Mostrar Todas Las Tarjetas");
        mnqMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnqMostrarTodoActionPerformed(evt);
            }
        });
        mnqVer.add(mnqMostrarTodo);

        mnqViajar.setText("Viajar");
        mnqViajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnqViajarActionPerformed(evt);
            }
        });
        mnqVer.add(mnqViajar);

        jMenuBar1.add(mnqVer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngresarActionPerformed
        VentanaIngreso ven=new VentanaIngreso(man);
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
        ven.setTitle("Ingreso TarjetaBip");
        ven.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_mnuIngresarActionPerformed

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        String codigo=JOptionPane.showInputDialog("Ingrese el Codigo de la TarjetaBip a Eliminar:");
        JOptionPane.showMessageDialog(this, man.eliminartarjeta(codigo),"Eliminar TarjetaBip",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_mnuEliminarActionPerformed

    private void mnqMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnqMostrarTodoActionPerformed
        VentanaMostrar ven=new VentanaMostrar(man);
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
        ven.setTitle("Mostrar TarjetaBip");
        ven.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_mnqMostrarTodoActionPerformed

    private void mnqViajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnqViajarActionPerformed
        String codigo=JOptionPane.showInputDialog("Ingrese el Codigo de la TarjetaBip a Viajar:");
        int pos=man.buscartarjeta(codigo);
        if(pos!=-1)
        {
            int valorpasaje=Integer.parseInt(JOptionPane.showInputDialog("Bienvenido a TransMetropolitano, Porfavor Pase la Tarjeta por el Validador:"));
            if(man.getTar().get(pos).getTotaldinero()>=valorpasaje)
            {
                JOptionPane.showMessageDialog(this, man.getTar().get(pos).viaje(valorpasaje));
            }
            else
            {
                JOptionPane.showMessageDialog(this, man.getTar().get(pos).viaje(valorpasaje));
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "La Tarjeta no Existe");
        }
    }//GEN-LAST:event_mnqViajarActionPerformed

    private void mnuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargarActionPerformed
        String codigo=JOptionPane.showInputDialog("Ingrese el Codigo de la TarjetaBip a Cargar:");
        int pos=man.buscartarjeta(codigo);
        if(pos!=-1)
        {
            int carga=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Monto a Cargar:"));
            JOptionPane.showMessageDialog(this, man.cargartarjeta(codigo, carga));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "La Tarjeta no Existe");
        }
    }//GEN-LAST:event_mnuCargarActionPerformed

    private void mnuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarActionPerformed
        String codigo=JOptionPane.showInputDialog("Ingrese el Codigo de la TarjetaBip a Modificar:");
        int pos=man.buscartarjeta(codigo);
        if(pos!=-1)
        {
            int totaldinero=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el Saldo a Modificar:"));
            man.getTar().get(pos).setTotaldinero(totaldinero);
            JOptionPane.showMessageDialog(this, "Saldo Modificado");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "La Tarjeta no Existe");
        }
        
    }//GEN-LAST:event_mnuModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem mnqMostrarTodo;
    private javax.swing.JMenu mnqTarjeta;
    private javax.swing.JMenu mnqVer;
    private javax.swing.JMenuItem mnqViajar;
    private javax.swing.JMenuItem mnuCargar;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuIngresar;
    private javax.swing.JMenuItem mnuModificar;
    // End of variables declaration//GEN-END:variables
}
